DROP TRIGGER l_dept_bir;
	
DROP TABLE USUARIO; /*Elimina la tabla completa*/

TRUNCATE TABLE USUARIO;
DELETE TABLE USUARIO;/*Copia de seguridad datos, es mas lento*/

UPDATE USUARIO SET edad = edad + 1;
SELECT * FROM USUARIO;
SELECT * FROM USUARIO WHERE edad >= 20 AND edad < 30;
SELECT nombre||':<'||email||'> tiene '||edad||' años' FROM USUARIO;
/* EL || SIRVE PARA CONCATENAR */

SELECT nombre, 2018 - edad AS anio_nacim FROM USUARIO;/*Para indicar la fecha de nacimiento por ejemplo*/

SELECT 'Hola, muy buenas' AS texto FROM dual; -- Texto tal cual
SELECT upper('Hola, muy buenas') AS texto FROM dual;
SELECT lower('Hola, muy buenas') AS texto FROM dual;

-------------------------------
/*Trigger edad < 18 */
-------------------------------

SELECT * FROM USUARIO WHERE edad NOT BETWEEN 20 AND 30;

SELECT NOMBRE, APELLIDOS FROM USUARIO WHERE APELLIDOS IS NULL;
--QUITAR ESPACIOS A LA DERECHA, IZQUIERDA O EN AMBOS LADOS--
SELECT RTRIM(DESCRIPCION) FROM USUARIO;
SELECT LTRIM(DESCRIPCION) FROM USUARIO;
SELECT TRIM(DESCRIPCION) FROM USUARIO;
--REEMPLAZAR TODOS POR CUALQUIERA--
SELECT REPLACE(DESCRIPCION, 'todos', 'cualquiera') FROM USUARIO;
--REEMPLAZA TODOS POR CUALQUIERA Y QUITA LOS *--
SELECT TRIM(BOTH '*' FROM REPLACE(DESCRIPCION, 'todos', 'cualquiera')) FROM USUARIO;
--MUESTRA LA DESCRIPCION DESDE EL CARACTER 3 AL 5 Y EL TAMAÑO DE ESTA--
SELECT SUBSTR(DESCRIPCION, 3, 5), LENGTH(DESCRIPCION) FROM USUARIO;

SELECT INSTR(DESCRIPCION, 'vago') FROM USUARIO;
--SUSTITUYE LAS VOCALES AEIOU POR 43102 RESPECTIVAMENTE: a=4, e=3...--
SELECT TRANSLATE(DESCRIPCION,'aeiou','43102') FROM USUARIO;



