--DEVUELVE UN NUMERO ALEATORIO ENTRE 1 Y 100--
SELECT dbms_random.value(1,100) FROM DUAL;
SELECT ROUND(dbms_random.value(1,100)) FROM DUAL;

ALTER TABLE USUARIO ADD NOTA NUMBER(4,2) DEFAULT 0;
UPDATE USUARIO SET NOTA=dbms_random.value(1,10);

SELECT CEIL(NOTA) FROM USUARIO;--REDONDE POR ENCIMA--
SELECT NOTA, FLOOR(NOTA) FROM USUARIO;--REDONDEA POR DEBAJO--
SELECT NOTA, ROUND(NOTA, 1) FROM USUARIO;--REDONDEA EL NUMERO DE DECIMAL QUE TU PONGAS--

SELECT NOTA, CEIL(NOTA), FLOOR(NOTA), ROUND(NOTA,1) FROM USUARIO;

SELECT ABS(-20), MOD(10,3), POWER(2,3) FROM DUAL;--ABS EL VALOR ABSOLUTO(VALOR POSITIVO), MOD EL RESTO Y POWER 2 ELEVADO A LA 3--
SELECT SIGN(5), SIGN(-3), SQRT(16) FROM DUAL;